// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atlasCDCPayroll.Data;

#nullable disable

namespace atlasCDCPayroll.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615045646_StaticSeedData")]
    partial class StaticSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("atlasCDCPayroll.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 101,
                            Designation = "Staff",
                            Email = "ram@company.com",
                            Level = "1",
                            Name = "Ram Employee",
                            Password = "ram123",
                            Phone = "555-0192",
                            Username = "ram"
                        });
                });

            modelBuilder.Entity("atlasCDCPayroll.Models.Payslip", b =>
                {
                    b.Property<int>("PayslipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DeductionForLeaves")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfLeaves")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SalaryPerDay")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("PayslipId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payslips");

                    b.HasData(
                        new
                        {
                            PayslipId = 1,
                            BasicSalary = 50000m,
                            DeductionForLeaves = 0m,
                            EmployeeId = 101,
                            GeneratedOn = new DateTime(2026, 6, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = 6,
                            MonthName = "June",
                            NetSalary = 50000m,
                            NoOfLeaves = 0,
                            SalaryPerDay = 1666.67m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("atlasCDCPayroll.Models.Payslip", b =>
                {
                    b.HasOne("atlasCDCPayroll.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
